controller_manager:
  ros__parameters:
    update_rate: 100
    
    pendulum_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pendulum_controller:
  ros__parameters:
    joints:
      - pendulum_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    joints:
      - pendulum_joint