controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    rover_control:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rover_control:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]
    
    wheel_separation: 0.24
    wheels_per_side: 2
    wheel_radius: 0.0325
    
    odom_frame_id: odom
    base_frame_id: base_footprint

    pose_covariance_diagonal: [0.025, 0.025, 0.001, 0.001, 0.001, 0.1]
    twist_covariance_diagonal: [0.025, 0.025, 0.001, 0.001, 0.001, 0.1]
    
    position_feedback: false
    open_loop: false
    enable_odom_tf: false  

    use_stamped_vel: false

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
    publish_rate: 30.0
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0 
        has_acceleration_limits: true
        max_acceleration: 0.3
        max_deceleration: -0.8 
    
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 4.0
        min_velocity: -4.0
        has_acceleration_limits: true
        max_acceleration: 2.0
        max_deceleration: -2.0   

# Joint state broadcaster
joint_state_broadcaster:
  ros__parameters:
    joints: 
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint
