controller_manager:
  ros__parameters:
    update_rate: 30 # Hz 

    rover_control:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rover_control:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]

    wheel_separation: 0.24      # 125 mm minimum distance between wheels
    wheels_per_side: 2           # actually 2, but both are controlled by 1 signal

    wheel_radius: 0.0325          # 32.5mm wheel radius

    odom_frame_id: odom
    base_frame_id: base_footprint

    publish_rate: 30.0

    pose_covariance_diagonal: [0.025, 0.025, 0.001, 0.001, 0.001, 0.1]
    twist_covariance_diagonal: [0.03, 0.03, 0.001, 0.001, 0.001, 0.1]

    position_feedback: false
    open_loop: false
    enable_odom_tf: false

    # Remove when moving to nav2
    use_stamped_vel: false

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear.x.has_velocity_limits: true 
    linear.x.has_acceleration_limits: true 
    linear.x.has_jerk_limits: false 
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 0.5
    linear.x.min_acceleration: -0.8
    linear.x.max_jerk: 0.3
    linear.x.min_jerk: -0.6

    angular.z.has_velocity_limits: true 
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
